spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gaoleigreat/springcloudrepo.git
          username: 513684652@qq.com
          password: gl19920709
  rabbitmq:
    host: 119.29.199.151
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7001
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.cloud.openfeign: debug